import asyncio
import sqlite3
from dataclasses import dataclass
from typing import List

import instructor
import litellm
from nanoid import generate
from pydantic import BaseModel

from quantalogic.tools import create_tool

# Constants
MODEL_NAME = "gemini/gemini-2.0-flash"
DB_PATH = "agent_tasks.db"
VALID_STATUSES = {'todo', 'in-progress', 'review', 'done', 'blocked'}

# Global client for AI interactions
client = instructor.from_litellm(litellm.acompletion)

# Database setup
conn = sqlite3.connect(DB_PATH, check_same_thread=False)
cursor = conn.cursor()

# Create tasks table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS tasks (
        task_id TEXT PRIMARY KEY,
        task_description TEXT NOT NULL
    )
''')

# Create subtasks table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS subtasks (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        task_id TEXT NOT NULL,
        step INTEGER NOT NULL,
        description TEXT NOT NULL,
        status TEXT DEFAULT 'todo' CHECK(status IN ('todo', 'in-progress', 'review', 'done', 'blocked')),
        FOREIGN KEY (task_id) REFERENCES tasks(task_id)
    )
''')
conn.commit()

# Dataclasses
@dataclass
class SubtaskWithStatus:
    """Subtask with status information.
    
    Attributes:
        step: The step number in the plan (1-based)
        description: Detailed description of the subtask
        status: Current status of the subtask. Must be one of: 
            'todo', 'in-progress', 'review', 'done', or 'blocked'
    """
    step: int
    description: str
    status: str = "todo"

class SubtaskResponse(BaseModel):
    step: int
    description: str

@dataclass
class PlanResult:
    """Result container for plan generation and retrieval."""
    task_id: str
    task_description: str
    subtasks: List[SubtaskWithStatus]

# Tools
@create_tool
async def create_project_plan(task_description: str, tools_description: str = None) -> PlanResult:
    """Generate an AI-powered project plan by decomposing a task.

    Args:
        task_description: Description of the main task to be planned.
        tools_description: Optional description of available tools to consider.

    Returns:
        PlanResult: A dataclass object containing the generated project plan with the following attributes:
            - task_id (str): A unique identifier for the task, prefixed with "task_" followed by a random nanoid (e.g., "task_abc123").
            - task_description (str): The original task description provided as input, preserved verbatim.
            - subtasks (List[SubtaskWithStatus]): A list of subtask objects, where each SubtaskWithStatus has:
                - step (int): A positive integer indicating the subtask's order in the plan (e.g., 1, 2, 3).
                - description (str): A detailed description of the subtask, generated by the AI model.
                - status (str): The initial status of the subtask, always set to "todo" for newly created subtasks.

    Raises:
        ValueError: If the AI response is malformed (not a list or missing required fields).
    """
    prompt = f"""
    Break down the following task into clear subtasks with steps:

    {task_description}

    {f"Consider the following tools for the task:\n\n{tools_description}" if tools_description else ""}

    Return the subtasks as a JSON array of objects, each with 'step' (integer) and 'description' (string) fields.
    """

    response = await client.create(
        model=MODEL_NAME,
        messages=[{"role": "user", "content": prompt}],
        response_model=List[SubtaskResponse]
    )

    # Validate AI response
    if not isinstance(response, list):
        raise ValueError(
            "The AI model returned an invalid response format. Expected a list of subtasks, "
            "but got a different type. Please check your prompt and try again with a different task description."
        )
    for subtask in response:
        if not isinstance(subtask, SubtaskResponse):
            raise ValueError(
                "Invalid subtask format in AI response. Each subtask must have 'step' (integer) "
                "and 'description' (string) fields. Please verify the model output format."
            )

    task_id = "task_" + generate()
    subtasks_with_status = [
        SubtaskWithStatus(step=subtask.step, description=subtask.description, status="todo")
        for subtask in response
    ]

    # Store in database within a transaction
    with conn:
        conn.execute('INSERT INTO tasks (task_id, task_description) VALUES (?, ?)', 
                     (task_id, task_description))
        conn.executemany(
            'INSERT INTO subtasks (task_id, step, description, status) VALUES (?, ?, ?, ?)',
            [(task_id, s.step, s.description, s.status) for s in subtasks_with_status]
        )

    return PlanResult(task_id=task_id, task_description=task_description, subtasks=subtasks_with_status)

@create_tool
async def retrieve_project_plan(task_id: str) -> PlanResult:
    """Retrieve a project plan for a specific task."""
    cursor = conn.cursor()
    cursor.execute('SELECT task_description FROM tasks WHERE task_id = ?', (task_id,))
    task_row = cursor.fetchone()
    if not task_row:
        raise ValueError(
            f"No project plan found for task ID '{task_id}'. "
            "Possible reasons:\n"
            "1. The task ID may be incorrect - verify the ID and try again\n"
            "2. The plan may have been deleted - create a new plan if needed"
        )
    
    cursor.execute('SELECT step, description, status FROM subtasks WHERE task_id = ? ORDER BY step', 
                   (task_id,))
    subtasks_rows = cursor.fetchall()
    
    subtasks = [SubtaskWithStatus(step=step, description=desc, status=status) 
                for step, desc, status in subtasks_rows]

    return PlanResult(task_id=task_id, task_description=task_row[0], subtasks=subtasks)

@create_tool
async def update_subtask_status_by_id(task_id: str, step: int, status: str) -> str:
    """Update status of a specific subtask within a project plan.
    
    Args:
        task_id: ID of the task containing the subtask
        step: Step number of the subtask to update
        status: New status for the subtask. Must be one of:
            'todo', 'in-progress', 'review', 'done', or 'blocked'
    
    Returns:
        str: Confirmation message of the update
    
    Raises:
        ValueError: If the status is invalid or subtask not found
    """
    status = status.lower()
    if status not in VALID_STATUSES:
        raise ValueError(
            f"Invalid status '{status}'. Valid statuses are: {sorted(VALID_STATUSES)}. "
            "Please use one of these predefined status values."
        )

    cursor = conn.cursor()
    cursor.execute('UPDATE subtasks SET status = ? WHERE task_id = ? AND step = ?', 
                   (status, task_id, step))
    conn.commit()
    
    if cursor.rowcount == 0:
        raise ValueError(
            f"Could not update subtask - no subtask found for task ID '{task_id}' and step {step}. "
            "Possible solutions:\n"
            f"1. Verify the task ID is correct using retrieve_project_plan('{task_id}')\n"
            f"2. Check the step number exists in the plan (valid steps: 1-{step})"
        )

    return f"Step {step} of task {task_id} updated to '{status}'."

# Demonstration
async def main():
    """Demonstrate the planning toolbox functionality."""
    try:
        print("🚀 Generating project plan...")
        plan = await create_project_plan("Develop a modern web application")
        print(f"\n📋 Project Details:\nTask ID: {plan.task_id}\nTask Description: {plan.task_description}")
        print("\n🔍 Initial Subtasks:")
        for s in plan.subtasks:
            print(f"Step {s.step}: {s.description} (Status: {s.status})")

        print(f"\n🔄 Updating status of Step {plan.subtasks[0].step}...")
        msg = await update_subtask_status_by_id(plan.task_id, plan.subtasks[0].step, "in-progress")
        print(msg)

        print("\n🔍 Updated Plan:")
        updated_plan = await retrieve_project_plan(plan.task_id)
        for s in updated_plan.subtasks:
            print(f"Step {s.step}: {s.description} (Status: {s.status})")

        try:
            await update_subtask_status_by_id(plan.task_id, 999, "done")
        except ValueError as e:
            print(f"\n❌ Expected error: {e}")

        print("\n✅ Demonstration completed successfully!")
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    asyncio.run(main())