name: Build quantalogic_hacker_news

on:
  push:
    branches-ignore: []
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Cache Poetry virtualenv
      id: cache-venv
      uses: actions/cache@v3
      with:
        path: toolboxes/quantalogic_hacker_news/.venv
        key: venv-${{ runner.os }}-${{ matrix.python-version }}-hacker-news-${{ hashFiles('toolboxes/quantalogic_hacker_news/poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ matrix.python-version }}-hacker-news-

    - name: Build package
      working-directory: toolboxes/quantalogic_hacker_news
      run: poetry build

    - name: Install package
      working-directory: toolboxes/quantalogic_hacker_news
      run: |
        pip install dist/*.whl
        poetry install --with dev

    - name: Test quantalogic_hacker_news version
      working-directory: toolboxes/quantalogic_hacker_news
      run: python -c "import quantalogic_hacker_news; print(quantalogic_hacker_news.__version__)"
